[package]
name = "winterm-rs"
version = "0.2.0"
edition = "2024"
license = "MIT"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
crossterm = "0.29"
rand = "0.9.2"
rand_distr = "0.5.1"

[dependencies.bevy]
version = "0.17.2"
default-features = false
features = ["std"]
